name: Flutter CI

on:
  push:
    branches: [main, master, develop, "*-develop-*"]
  pull_request:
    branches: [main, master, develop]

# 取消正在运行的相同工作流
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 构建Web
  build-web:
    name: 构建Web
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: 📥 检出代码
        uses: actions/checkout@v4

      - name: 🐦 设置Flutter环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.1"
          dart-version: "3.7.0"
          channel: "stable"
          cache: true

      - name: 🌐 构建Web
        run: make build-web

      - name: 📦 上传Web构建产物
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
          retention-days: 30
